### ISSUE TITLE
TSP Parsing

### ISSUE THREAD

**Issue by Barbapoulpe** [thiagodnf/jacof#4]
In TSPLIBReader, the separator should be 
`String[] split = line.split("\\s+");`
since the TSPLib sometimes separates coordinates using more than one space (to keep the column alignment consistent) and just using spaces can make files unreadable.

**Comment by thiagodnf** [comment]
Hello @Barbapoulpe 

How are you?

Thanks a lot for your comment. I just committed this suggestion and I coded some unit tests.
